name: Node.js CI
on: [push, pull_request]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Find yarn cache
        id: find-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: git checkout
        uses: actions/checkout@v2
      - name: Cache yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{steps.find-yarn-cache.outputs.dir}}
          key: ${{runner.os}}-node${{node-version}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{node-version}}-yarn-
      - name: Set up Node.js v${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn
      - run: yarn test
    env:
      CI: true
